# https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/

splash = true
ipc = true
wallpaper {
    monitor = eDP-1
    # Use absolute path instead of ~/
    path = $HOME/wokemarchy/wallpapers/1-city-view.png
    fit_mode = cover
}

#TODO: make a script to loop through available displays
wallpaper {
    monitor = DP-1
    path = $HOME/wokemarchy/wallpapers/1-city-view.png
    fit_mode = cover
  }

wallpaper {
    monitor = DP-2
    # Use absolute path instead of ~/
    path = $HOME/wokemarchy/wallpapers/1-city-view.png
    fit_mode = cover
}
